export const LOAD_INSTANCES_BEGIN = "LOAD_INSTANCES_BEGIN";
export const LOAD_INSTANCES_END = "LOAD_INSTANCES_END";

export const EDITING_GAME_BEGIN = "EDITING_GAME_BEGIN";
export const EDITING_GAME_ABORT = "EDITING_GAME_ABORT";
export const EDITING_GAME_VALUE_CHANGE = "EDITING_GAME_VALUE_CHANGE";
export const EDITING_BEGIN_SAVING = "EDITING_BEGIN_SAVING";
export const EDITING_DONE_SAVING = "EDITING_DONE_SAVING";

export const LAUNCHING_GAME_BEGIN = "LAUNCHING_GAME_BEGIN";
export const LAUNCHING_GAME_ABORT = "LAUNCHING_GAME_ABORT";
export const LAUNCHING_GAME_UPDATE_INFO = "LAUNCHING_GAME_UPDATE_INFO";
export const LAUNCHING_GAME_IN_PROGRESS = "LAUNCHING_GAME_IN_PROGRESS";
export const LAUNCHING_GANE_DONE = "LAUNCHING_GANE_DONE";
