language: csharp
solution: factorio.sln
mono: none
dotnet: 2.2.6
install:
  - nuget restore factorio.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
 - msbuild /p:Configuration=Release factorio.sln
 - mono ./testrunner/xunit.runnsers.1.9.2/tools/xunit.console.clr4.exe ./Factorio.Test/bin/Release/Factorio.Test.dll
